export interface ConfigSeedEntry {
  key: string;
  value: unknown;
  valueType: "string" | "number" | "boolean" | "json";
  isPublic: boolean;
  description: string;
}

export const DEFAULT_CONFIG: ConfigSeedEntry[] = [
  {
    key: "business.name",
    value: "DULCERA CAR",
    valueType: "string",
    isPublic: true,
    description: "Nombre comercial",
  },
  {
    key: "business.tagline",
    value: "Dulces Personalizados y Etiquetas Suajadas al Mayoreo",
    valueType: "string",
    isPublic: true,
    description: "Eslogan",
  },
  {
    key: "business.hero_title",
    value: "Haz que tu Marca\nsea el Regalo\nmás Dulce",
    valueType: "string",
    isPublic: true,
    description: "Título principal del inicio",
  },
  {
    key: "business.shipping_message",
    value: "Enviamos a todo México",
    valueType: "string",
    isPublic: true,
    description: "Mensaje de envío",
  },
  {
    key: "business.wholesale_note",
    value: "Pedidos de 20,000 piezas o más en dulces califican para precio especial mayorista.",
    valueType: "string",
    isPublic: true,
    description: "Nota de mayoreo",
  },
  {
    key: "contact.phones",
    value: [
      { number: "3313287031", label: "Oficina principal" },
      { number: "3331716483", label: "Ventas" },
      { number: "3311500317", label: "Atención a clientes" },
    ],
    valueType: "json",
    isPublic: true,
    description: "Teléfonos de contacto",
  },
  {
    key: "contact.whatsapp_message",
    value: "Hola, me interesa hacer un pedido de Dulces o Etiquetas Personalizadas al Mayoreo.",
    valueType: "string",
    isPublic: true,
    description: "Mensaje predeterminado de WhatsApp",
  },
  {
    key: "contact.hours",
    value: "Lunes a Viernes · 9:00 am – 6:00 pm\nSábado · 9:00 am – 2:00 pm",
    valueType: "string",
    isPublic: true,
    description: "Horario de atención",
  },
  {
    key: "sales.vendedores",
    value: [
      { label: "Ventas 1", phone: "3313287031" },
      { label: "Ventas 2", phone: "3331716483" },
      { label: "Ventas 3", phone: "3311500317" },
    ],
    valueType: "json",
    isPublic: true,
    description: "Representantes de ventas para pre-órdenes",
  },
  {
    key: "tax.iva_rate",
    value: 0.16,
    valueType: "number",
    isPublic: true,
    description: "Tasa IVA",
  },
  {
    key: "tax.ieps_rate",
    value: 0.08,
    valueType: "number",
    isPublic: true,
    description: "Tasa IEPS (dulces no chicle)",
  },
  {
    key: "discounts.codes",
    value: {
      DULCE10: { pct: 10, label: "10% de descuento" },
      PROMO15: { pct: 15, label: "15% de descuento" },
      MAYOREO20: { pct: 20, label: "20% de descuento" },
      BIENVENIDO: { pct: 5, label: "5% bienvenida" },
    },
    valueType: "json",
    isPublic: true,
    description: "Códigos de descuento",
  },
  {
    key: "pricing.catalog",
    value: {
      products: {
        dulces: {
          id: "dulces",
          name: "Dulces Personalizados",
          basePrice: 0.42,
          minQty: 10000,
        },
        etiquetas: {
          id: "etiquetas",
          name: "Etiquetas Personalizadas",
          basePrice: 0.85,
          minQty: 5000,
        },
      },
      sizes: {
        dulces: ["Mini (5.5cm x 2.5cm)", "Mediano (7cm x 4cm)", "Grande (8cm x 4cm)"],
        etiquetas: [],
      },
      shapes: {
        dulces: [],
        etiquetas: ["Circular", "Rectangular", "Ovalado", "Mermelada"],
      },
      dulcesCatalog: {
        "Mini (5.5cm x 2.5cm)": [
          { tipo: "Bola Tamarindo – Mango – Piña", precioBolsa: 400, esChicle: false },
        ],
        "Mediano (7cm x 4cm)": [
          { tipo: "Bola Tamarindo Mango Piña", precioBolsa: 420, esChicle: false },
          { tipo: "Gragea Menta y Tamarindo", precioBolsa: 430, esChicle: false },
          { tipo: "Bola Menta Inglesa", precioBolsa: 430, esChicle: false },
          { tipo: "Pastillas comprimidas Mango – Menta – Aciditos", precioBolsa: 550, esChicle: false },
          { tipo: "Chicle Frutas", precioBolsa: 520, esChicle: true },
          { tipo: "Luneta Chocomenta", precioBolsa: 640, esChicle: false },
        ],
        "Grande (8cm x 4cm)": [
          { tipo: "Bola Tamarindo Mango Piña 2 pz", precioBolsa: 450, esChicle: false },
          { tipo: "Gragea Menta y Tamarindo", precioBolsa: 460, esChicle: false },
          { tipo: "Pastillas comprimidas Mango – Menta – Aciditos", precioBolsa: 560, esChicle: false },
          { tipo: "Chicle Frutas", precioBolsa: 530, esChicle: true },
          { tipo: "Luneta Chocomenta", precioBolsa: 650, esChicle: false },
        ],
      },
      dulcesTintaPrices: { 1: 200, 2: 400, 3: 600 },
      etiquetaSizesByShape: {
        Circular: ["3 cm", "5 cm", "7 cm", "8.5 cm", "10 cm"],
        Rectangular: [
          "2.1×2.25 cm", "2.2×3.2 cm", "2.5×15.5 cm", "2.9×7 cm",
          "3.2×7.6 cm", "3.3×4.4 cm", "3.5×6.8 cm", "4.5×18.07 cm",
          "5×7.7 cm", "5.07×3.18 cm", "5.08×10.16 cm", "5.4×7.5 cm",
          "6.2×8 cm", "6.2×13.5 cm", "7×5.8 cm", "7.6×11.5 cm",
          "7.6×15.6 cm", "7.6×17.8 cm", "8.9×12.5 cm", "10×17.6 cm", "14×15 cm",
        ],
        Ovalado: ["3×3.5 cm", "4.5×7.5 cm"],
        Mermelada: ["2.9×5 cm"],
      },
      etiquetaBasePrices: {
        "3 cm": 724.98,
        "5 cm": 1302.74,
        "7 cm": 2169.36,
        "8.5 cm": 2169.36,
        "10 cm": 4010.94,
        "2.1×2.25 cm": 574.41,
        "2.2×3.2 cm": 654.21,
        "2.5×15.5 cm": 1799.24,
        "2.9×7 cm": 1133.02,
        "3.2×7.6 cm": 1278.18,
        "3.3×4.4 cm": 924.31,
        "3.5×6.8 cm": 1259.4,
        "4.5×18.07 cm": 3341.11,
        "5×7.7 cm": 1790.21,
        "5.07×3.18 cm": 982.18,
        "5.08×10.16 cm": 2263.71,
        "5.4×7.5 cm": 1862.43,
        "6.2×8 cm": 2191.03,
        "6.2×13.5 cm": 3422.36,
        "7×5.8 cm": 1866.04,
        "7.6×11.5 cm": 3555.96,
        "7.6×15.6 cm": 4681.13,
        "7.6×17.8 cm": 5284.88,
        "8.9×12.5 cm": 4417.17,
        "10×17.6 cm": 6755.26,
        "14×15 cm": 7982.98,
        "3×3.5 cm": 779.15,
        "4.5×7.5 cm": 1618.69,
        "2.9×5 cm": 923.59,
      },
      etiquetaColorSurcharge: 200,
      etiquetaMaxColors: 5,
      materialsEtiquetas: [
        "Papel Couche",
        "Papel Transparente",
        "Papel Pegamento Extra-Refrigeración",
        "Papel Metalizado Plata",
      ],
      finishes: ["Laminado"],
    },
    valueType: "json",
    isPublic: true,
    description: "Catálogo de productos y precios",
  },
  {
    key: "terms.conditions",
    value: [
      {
        id: "minimos",
        icon: "package",
        title: "Mínimos de Pedido",
        items: [
          { label: "Dulces Personalizados", text: "10,000 piezas (10 bolsas de 1,000 pzas cada una)." },
          { label: "Etiquetas en Rollo", text: "5,000 piezas por pedido." },
          { text: "Los pedidos por debajo del mínimo no pueden ser procesados." },
        ],
      },
      {
        id: "tiempos",
        icon: "clock",
        title: "Tiempos de Producción y Entrega",
        items: [
          { label: "Primer pedido", text: "20 a 25 días hábiles a partir de la aprobación del arte y confirmación del pago." },
          { label: "Reórdenes", text: "15 a 20 días hábiles (cuando el arte ya está aprobado)." },
          { label: "Temporada alta", text: "Los tiempos pueden extenderse en noviembre-diciembre. Consultar disponibilidad." },
          { text: "Los tiempos de entrega son aproximados y no incluyen el tiempo de envío al destino final." },
        ],
      },
      {
        id: "arte",
        icon: "edit-3",
        title: "Arte y Diseño",
        items: [
          { label: "Formatos aceptados", text: ".AI (Illustrator), .PDF vectorial, .PNG con fondo transparente a 300 dpi mínimo." },
          { label: "Revisión de arte", text: "Dulcera Car realiza una revisión técnica. Si el arte no cumple los requisitos, se notificará al cliente antes de iniciar producción." },
          { label: "Prueba de impresión", text: "Se envía una prueba digital para aprobación del cliente antes de imprimir. La producción inicia hasta recibir aprobación por escrito." },
          { label: "Ajustes de arte", text: "Cambios menores de diseño (color, texto) pueden generar un costo adicional de ajuste. Diseño desde cero se cotiza por separado." },
        ],
      },
      {
        id: "pago",
        icon: "credit-card",
        title: "Condiciones de Pago",
        items: [
          { label: "Anticipo y Liquidación", text: "50% antes de empezar a trabajar en el diseño, y 50% contra entrega en Guadalajara, Jalisco. Para clientes al interior de la República Mexicana, se debe liquidar el 100% antes de empezar a trabajar en el diseño." },
          { label: "Formas de pago", text: "Transferencia bancaria, depósito o pago en efectivo. Consultar datos bancarios al confirmar pedido." },
          { text: "El pedido no se libera hasta tener el pago completo." },
        ],
      },
      {
        id: "envio",
        icon: "truck",
        title: "Envío y Logística",
        items: [
          { text: "Enviamos a todo México mediante paqueterías de confianza." },
          { label: "Costo de envío", text: "Se cotiza por separado según el peso, volumen y destino. No está incluido en el precio de producción." },
          { label: "Riesgo de envío", text: "Una vez entregado a la paquetería, el cliente asume la responsabilidad del envío. Recomendamos solicitar seguro de envío para pedidos grandes." },
        ],
      },
      {
        id: "modificaciones",
        icon: "refresh-cw",
        title: "Modificaciones y Cancelaciones",
        items: [
          { label: "Antes de aprobación de arte", text: "Se pueden realizar cambios sin costo adicional." },
          { label: "Cancelaciones", text: "Si la producción ya inició, el anticipo no es reembolsable. Si aún no ha iniciado, se evalúa caso por caso." },
        ],
      },
      {
        id: "precios",
        icon: "tag",
        title: "Precios y Vigencia",
        items: [
          { text: "Todos los precios mostrados en la app son estimados y están sujetos a confirmación." },
          { label: "Vigencia", text: "Las cotizaciones tienen una vigencia de 15 días naturales a partir de su emisión." },
          { label: "IVA y IEPS", text: "Los precios son más los impuestos aplicables (IVA 16% / IEPS 8%)." },
          { label: "Mayoreo especial", text: "Pedidos de 20,000 piezas o más en dulces califican para precio especial mayorista. Consultar." },
        ],
      },
    ],
    valueType: "json",
    isPublic: true,
    description: "Condiciones comerciales",
  },
];
